config/routes.rb
Rails.application.routes.draw do
  root 'html_pages#home'

  get 'about_shed_finder'   => 'html_pages#about_shed_finder'
  get 'contact' => 'html_pages#contact'
  get 'sell_shed_antlers' => 'html_pages#sell_shed_antlers'
  get 'buy_shed_antlers' => 'html_pages#buy_shed_antlers'
  get 'buy_antler_dog_chews' => 'html_pages#buy_antler_dog_chews'
  get 'form_success' => 'html_pages#form_success'

 resources :users
 resources :chew_orders
 resources :messages
 resources :listings

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get 'user_dashboard' => 'users#user_dashboard'

end

app/models/chew_order.rb
class ChewOrder < ActiveRecord::Base
    validate :select_grade

    validates :name, :phone, :antlertype, :address, :message,
              presence: true

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :email,
            presence: true,
            format: { with: VALID_EMAIL_REGEX }

    def select_grade
        errors.add(:base, "Please select at least one grade") unless gradea || gradeb || gradec
    end

end

app/models/listing.rb
class Listing < ActiveRecord::Base
    belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
    validates :name, :phone, :message,
              presence: true

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :email,
            presence: true,
            format: { with: VALID_EMAIL_REGEX }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :listings
  validate :atleast_one_is_checked
  has_secure_password

  before_save { |user| user.email = email.downcase }

  validates :name,
            presence: true,
            length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i


  validates :email,
            presence: true,
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }


  validates :password,
            length: { minimum: 6 }


  validates :phone, :location,
            presence: true


  def atleast_one_is_checked
      errors.add(:base, "Select at least one checkbox") unless seller || buyer
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/chew_orders_controller.rb
class ChewOrdersController < ApplicationController
    def new
        @cheworder = ChewOrder.new
    end

    def create
        @cheworder = ChewOrder.new(order_params)
        if @cheworder.save
            #       Sends email to user when user is created.
        #SendEmailJob.set(wait: 20.seconds).perform_later(@user)
        EmailChewOrder.send_admin_chew_order(@cheworder).deliver_now
            redirect_to '/form_success'
        else
            render 'new'
        end
    end

    private

    def order_params
        params.require(:chew_order).permit(:name, :email, :phone, :address, :antlertype, :gradea, :gradeb, :gradec, :message)
    end
end

app/controllers/html_pages_controller.rb
class HtmlPagesController < ApplicationController
  def home
  end

  def about
  end

    def contact
      @contact = Contact.contact(contact_params)

      if @contact.save

#       Sends email to user when user is created.
        #SendEmailJob.set(wait: 20.seconds).perform_later(@user)
       # EmailUserRegistration.send_admin_user_registration(@user).deliver_now

          redirect_to '/form_success'
      else
        render 'new'
      end

  end

  def login
  end

  def shed_antler_sellers
  end

     private

      def contact_params
          params.require(:contact).permit(:name, :email, :phone, :message)
      end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def new
      @lising = Listing.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
      @message = Message.new
  end

    def create
        @message = Message.new(message_params)
        if @message.save
            #       Sends email to user when user is created.
        #SendEmailJob.set(wait: 20.seconds).perform_later(@user)
            EmailAdminMessage.send_admin_message(@message).deliver_now
            redirect_to '/form_success'
        else
            render 'new'
        end
    end

    private

    def message_params
        params.require(:message).permit(:name, :email, :phone, :message)
    end
end

app/controllers/sessions_controller.rb
# app/controllers/sessions_controller.rb

class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
        redirect_to '/user_dashboard'
    else
    # If user's login doesn't work, send them back to the login form.
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
        #redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    #this means they have to be logged in to see this page
    #before_filter :authorize <- this is restric all
    before_filter :require_login, only: [:edit, :destroy, :update]

  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save

#       Sends email to user when user is created.
        #SendEmailJob.set(wait: 20.seconds).perform_later(@user)
        EmailUserRegistration.send_admin_user_registration(@user).deliver_now

      session[:user_id] = @user.id
        redirect_to '/user_dashboard'
    else
        render 'new'
    end

  end



  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      #flash[:success] = "Profile updated"
        redirect_to '/user_dashboard'

    else
      render 'edit'
    end
  end

  private

      def user_params
          params.require(:user).permit(:name, :email, :password, :password_confirmation, :phone, :location, :buyer, :seller)
      end

    def require_login
    unless current_user
      redirect_to login_url
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chew_orders_helper.rb
module ChewOrdersHelper
end

app/helpers/html_pages_helper.rb
module HtmlPagesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auth_pages/auth_dashboard.html.erb
<% provide(:title, "Dashboard") %>
<!-- Main -->
					<article id="main">
						<header class="smallHeader">
							<h1><%= current_user.name %>'s Dashboard</h1>
						</header>
						<section class="wrapper style5">
							<div class="inner">
                                <% if current_user.admin == true %>

                                <% end %>
                              <%= link_to "Settings", edit_user_path(current_user) %>

							</div>
						</section>
					</article>
<%= render 'layouts/footer' %>

app/views/chew_orders/new.html.erb
<%
    provide(:title, "Buy Antler Dog Chews")
$type = [
    ['- Type -',''],
    ['Elk','elk'],
    ['Mule','mule'],
    ['Whitetail','whitetail'],
    ['Moose','moose'],
    ['Other','other']
    ]
%>
<!-- Main -->
<article id="main">
    <header>
        <h1>Buy Antler Dog Chews</h1>
        <p>Buy all natural dog chews</p>
    </header>
    <section class="wrapper style5">
        <div class="inner">



            <%= form_for @cheworder do |f| %>
                <% if @cheworder.errors.any? %>
                      <h2 style="color:#f00">Errors:</h2>
                        <ul>
                            <% @cheworder.errors.full_messages.each do |message| %>
                            <li style="color:#f00"><%= message %></li>
                            <% end %>
                        </ul>
            <% else %>
            <h4>Contact us for antler chew pricing</h4>
            <p><img alt="Buy All Natural Antler Dog Chews" title="Buy All Natural Antler Dog Chews" class="image right" src="/assets/buy-antler-dog-chews.jpg"/></p>

            <p>Dogs love antler chews and Shed finder can fill any order of any size. We cut our own chews and any order can be customized to meet your specific needs. We offer:   </p>
            <ul>
                <li>Custom orders</li>
                <li>Cheapest prices</li>
                <li>All natural chews</li>
                <li>Variety of chews </li>
                <li>Cut to order</li>
            </ul>

            <hr />
            <% end %>
                    <div class="row uniform">
                        <div class="6u 12u$(xsmall)">
                            <%= f.text_field :name, :placeholder => "First & Last Name" %>
                        </div>
                        <div class="6u$ 12u$(xsmall)">
                            <%= f.text_field :email, :placeholder => "Email" %>
                        </div>
                        <div class="6u 12u$(xsmall)">
                            <%= f.text_field :phone, :placeholder => "Phone" %>
                        </div>
                        <div class="6u$ 12u$(xsmall)">
                            <%= f.text_field :address, :placeholder => "Ship To Address" %>
                        </div>

                        <div class="12u$ 12u$(xsmall)">
                            <div class="select-wrapper">
                                <%= f.select :antlertype, options_for_select($type, {:selected => @cheworder.antlertype}) %>
                            </div>
                        </div>

                        <div class="4u 12u$(small)">
                            <%= f.check_box :gradea %>
                            <label for="chew_order_gradea">Grade A</label>
                        </div>
                        <div class="4u 12u$(small)">
                            <%= f.check_box :gradeb %>
                            <label for="chew_order_gradeb">Grade B</label>
                        </div>
                        <div class="4u$ 12u$(small)">
                            <%= f.check_box :gradec %>
                            <label for="chew_order_gradec">Grade C</label>
                        </div>

                        <div class="12u$">
                            <%= f.text_area :message, :placeholder => "Enter detailed message (cut size, poundage...)" %>
                    </div>

                        <div class="12u$">
                        <ul class="actions">
                            <li><%= f.submit "Get Quote", :class=> 'special' %></li>
                            <% if @cheworder.new_record? %>
                            <li><input type="reset" value="Reset" /></li>
                            <% end %>
                        </ul>
                     </div>
                    </div>
            <% end %>
        </div>
    </section>
</article>
<%= render 'layouts/footer' %>

app/views/email_admin_message/send_admin_message.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
      <h1><%= @message.name %> - created a new message</h1>
    <ul>
        <li>Email:      <%= @message.email %></li>
        <li>Phone:      <%= @message.phone %></li>

    </ul>
      <p>Message: <br/>
          <%= @message.message %>
      </p>
  </body>
</html>

app/views/email_admin_message/send_admin_message.txt.erb
<%= @message.name %> - created a chew order
        Email:      <%= @message.email %>
        Phone:      <%= @message.phone %>
Message: <%= @message.message %>

app/views/email_chew_order/send_admin_chew_order.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
      <h1><%= @cheworder.name %> - created a chew order</h1>
    <ul>
        <li>Email:      <%= @cheworder.email %></li>
        <li>Phone:      <%= @cheworder.phone %></li>
        <li>Address:    <%= @cheworder.address %></li>
        <li>Type:       <%= @cheworder.antlertype %></li>
        <li>Grade A:    <%= @cheworder.gradea %></li>
        <li>Grade B:    <%= @cheworder.gradeb %></li>
        <li>Grade C:    <%= @cheworder.gradec %></li>
    </ul>
      <p>Message: <br/>
          <%= @cheworder.message %>
      </p>
  </body>
</html>

app/views/email_chew_order/send_admin_chew_order.txt.erb
<%= @cheworder.name %> - created a chew order
        Email:      <%= @cheworder.email %>
        Phone:      <%= @cheworder.phone %>
        Address:    <%= @cheworder.address %>
        Type:       <%= @cheworder.antlertype %>
        Grade A:    <%= @cheworder.gradea %>
        Grade B:    <%= @cheworder.gradeb %>
    Grade C:    <%= @cheworder.gradec %>
Message: <%= @cheworder.message %>

app/views/email_user_registration/send_admin_user_registration.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>User: <%= @user.name %> was created</h1>
    <ul>
        <li>Email:      <%= @user.email %></li>
        <li>Phone:      <%= @user.phone %></li>
        <li>Location:   <%= @user.location %></li>
        <li>Buyer:      <%= @user.buyer %></li>
        <li>Seller:     <%= @user.seller %></li>
    </ul>
  </body>
</html>

app/views/email_user_registration/send_admin_user_registration.txt.erb
User <%= @user.name %> was created
        Email:      <%= @user.email %>
        Phone:      <%= @user.phone %>
        Location:   <%= @user.location %>
        Buyer:      <%= @user.buyer %>
        Seller:     <%= @user.seller %>

app/views/html_pages/about_shed_finder.html.erb
<% provide(:title, "About Shed Finder") %>
<!-- Main -->
					<article id="main">
						<header>
							<h1>About Shed Finder</h1>
							<p>We bring shed antler buyers and sellers together</p>
						</header>
						<section class="wrapper style5">
							<div class="inner">

								<h3>Why we built Shed Finder</h3>
								<p><img alt="Buy Antler Dog Chews" title="Buy Antler Dog Chews" class="contentImageRight" src="/assets/about-shed-finder.jpg"/></p>

								<p>Shed Finder was created to fill a need and bring shed antler sellers and buyers together. As a seller there is no great place to list your antlers and that is why Shed Finder was born. In recent years shed hunting has become more and more popular, meaning more people are collecting and selling antlers. With this boom in hunting many people are looking for a way to make some extra money buy selling excess antlers. We make is easy to post your antlers online and receive at least one bid.    </p>

								<hr />

								<h4>About Me</h4>
								<p>I am a web developer and an outdoor enthusiast and when I discovered the huge market for shed antlers I decided to create Shed Finder.I currently live in northern Colorado with my wife and daughter. We love hiking, four wheeling, and pretty much anything outdoors. Please feel free to <%= link_to "contact", contact_path %> me with any questions you may have, I'm always happy to hear from other outdoor enthusiasts.</p>
							</div>
						</section>
					</article>
<%= render 'layouts/footer' %>

app/views/html_pages/buy_antler_dog_chews.html.erb
<% provide(:title, "Buy Antler Dog Chews") %>
<!-- Main -->
<article id="main">
    <header>
        <h1>Buy Antler Dog Chews</h1>
        <p>Buy all natural dog chews</p>
    </header>
    <section class="wrapper style5">
        <div class="inner">

            <h3>Buy All Nautural Antler Dog Chews</h3>
            <p><img alt="Buy All Natural Antler Dog Chews" title="Buy All Natural Antler Dog Chews" class="image right" src="/assets/buy-antler-dog-chews.jpg"/></p>

            <p>Dogs love antler chews and Shed finder can fill any order of any size. We cut our own chews and any order can be customized to meet your specific needs. We offer:   </p>
            <ul>
                <li>Custom orders</li>
                <li>Cheapest prices</li>
                <li>All natural chews</li>
                <li>Variety of chews </li>
                <li>Cut to order</li>
            </ul>

            <hr />

            <h4>Contact us for antler chew pricing</h4>
            <form method="post" action="#">
                <div class="row uniform">
                    <div class="6u 12u$(xsmall)">
                        <input type="text" name="chew-name" id="chew-name" value="" placeholder="Name" />
                    </div>
                    <div class="6u$ 12u$(xsmall)">
                        <input type="email" name="chew-email" id="chew-email" value="" placeholder="Email" />
                    </div>
                    <div class="6u 12u$(xsmall)">
                        <input type="text" name="chew-number" id="chew-number" value="" placeholder="Phone" />
                    </div>
                    <div class="6u$ 12u$(xsmall)">
                        <div class="select-wrapper">
                            <select name="chew-type" id="chew-type">
                                <option value="">- Type -</option>
                                <option value="elk">Elk</option>
                                <option value="mule">Mule</option>
                                <option value="whitetail">Whitetail</option>
                                <option value="moose">Moose</option>
                            </select>
                        </div>
                    </div>
                    <div class="4u 12u$(small)">
                        <input type="checkbox" id="grade-a" name="chew-gradea" checked>
                        <label for="grade-a">Grade A</label>
                    </div>
                    <div class="4u 12u$(small)">
                        <input type="checkbox" id="grade-b" name="chew-gradeb">
                        <label for="grade-b">Grade B</label>
                    </div>
                    <div class="4u$ 12u$(small)">
                        <input type="checkbox" id="grade-c" name="chew-gradec">
                        <label for="grade-c">Grade C</label>
                    </div>
                    <div class="6u$ 12u$(small)">
                        <input type="checkbox" id="demo-human" name="demo-human" >
                        <label for="demo-human">Not spam</label>
                    </div>
                    <div class="12u$">
                        <textarea name="chew-message" id="chew-message" placeholder="Enter detailed message (cut size, poundage...)" rows="6"></textarea>
                    </div>
                    <div class="12u$">
                        <ul class="actions">
                            <li><input type="submit" value="Send Message" class="special" /></li>
                            <li><input type="reset" value="Reset" /></li>
                        </ul>
                    </div>
                </div>
            </form>

        </div>
    </section>
</article>
<%= render 'layouts/footer' %>

app/views/html_pages/buy_shed_antlers.html.erb
<% provide(:title, "Buy Shed Antlers Online") %>
<!-- Main -->
					<article id="main">
						<header>
							<h1>Buy Shed Antlers Online</h1>
							<p>Find different types of antlers online</p>
						</header>
						<section class="wrapper style5">
							<div class="inner">

								<h3>Why buy shed antlers from Shed Finder?</h3>
								<p></p>
<img alt="Buy Shed Antlers Online" title="Buy Shed Antlers Online" class="image right" src="/assets/sell-shed-antlers.jpg"/>
								<p>There are several reasons to use Shed Finder to buy antlers:
                                    <ul>
                                        <li>Small fee if you win your bid</li>
                                        <li>It's EASY!</li>
                                        <li>Access to tons of antlers </li>
                                        <li>Find leads you might not have not known about</li>
                                        <li>Mulitple listings</li>
                                        <li>No obligation to buy</li>
                                    </ul>
                                </p>
                            <hr/>
                            <p>
                                There is no cost for signing up, it's absolutely <span class="green">FREE</span>! The only cost to you is when you win a bid. Shed Finder charges a small 'Finders Fee' (2 cents for every 1 dollar).
                            </p>
                            <hr/>
                            <h3>How it works</h3>
                            <ol>
                                <li>Sign up for FREE</li>
                                <li>Get alerts when a new listing is available</li>
                                <li>Bid on the antler listing</li>
                                <li>If you win, you pay 2 cents for every dollar ($200 bid would cost you $4)</li>
                                <li>Pay the 'Finders Fee'</li>
                                <li>Get the listings contact information</li>
                            </ol>
                            <ul class="actions" style="text-align:right">
								<li><span class="button special"><%= link_to "Sign Up", controller: "users", action: "new", id: @users %></span></li>
							</ul>

							</div>
						</section>
					</article>
<%= render 'layouts/footer' %>

app/views/html_pages/form_success.html.erb
<% provide(:title, "Shed Finder Sign Up Success!") %>

<!-- Main -->
					<article id="main">
						<header>
							<h1>Shed Finder Form Success!</h1>
						</header>
						<section class="wrapper style5">
							<div class="inner">

                            <p>
                                <span style="font-size:35px;" class="green">Success! Form submitted.</span>
                            </p>

							</div>
						</section>
					</article>
<%= render 'layouts/footer' %>

app/views/html_pages/home.html.erb
<% provide(:title, "Shed Finder") %>



				<!-- Banner -->
					<section id="banner">
						<div class="inner">
							<h2>Shed Finder</h2>
							<p>Buy & Sell your shed antlers online.<br />
							Shed finder brings antler sellers and antler buyers together.<br />
							Top dollar for shed antlers!</p>
							<ul class="actions">
                                <li><span class="button special"><%= link_to "Sign Up", controller: "users", action: "new", id: @users %></span></li>
							</ul>
						</div>
<!--						<a href="#one" class="more scrolly">Learn More</a>-->
					</section>

				<!-- One -->
					<section id="one" class="wrapper style1 special">
						<div class="inner">
							<header class="major">
								<h2>Elk Sheds | Whitetail Sheds | Moose Sheds | Mule Sheds </h2>
								<p>Shed finder accepts all kinds of sheds. Get listed for <span class="yellow">FREE!</span><br />
								We also accept all conditons, grade A, grade B, & grade C. Everything from chaulk sheds to brown sheds!</p>
							</header>
							<ul class="icons major">
								<li><img width="100px" src="assets/elk.png" alt="" /></li>
								<li><img width="100px" src="assets/whitetail.png" alt="" /></li>
								<li><img width="100px" src="assets/moose.png" alt="" /></li>
                                <li><img width="100px" src="assets/mule.png" alt="" /></li>
							</ul>
						</div>
					</section>

				<!-- Two -->
					<section id="two" class="wrapper alt style2">
						<section class="spotlight">
							<div class="image"><img alt="Sell My Shed Antlers" title="Sell My Shed Antlers" src="assets/pic01.jpg" alt="" /></div><div class="content">
								<h2>Sell Your Antlers !!</h2>
								<p>List your shed antlers online to receive offers. We <span class="yellow">GAURANTEE</span> you will receive at least one offer!!</p>
                            <ul class="actions">
                                <li><span class="button special"><%= link_to "Start Selling", controller: "users", action: "new", id: @users %></span></li>
							</ul>
							</div>
						</section>
						<section class="spotlight">
							<div class="image"><img alt="Buy Shed Antlers" title="Buy Shed Antlers" src="assets/buy-shed-antlers.jpg" alt="" /></div><div class="content">
								<h2>Buy Antlers Now!!</h2>
								<p>Sign up for <span class="yellow">FREE</span> to access our complete list of antler for sale.</p>
                            <ul class="actions">
                                <li><span class="button special"><%= link_to "Buy Antlers", controller: "users", action: "new", id: @users %></span></li>
							</ul>
							</div>
						</section>
						<section class="spotlight">
							<div class="image"><img alt="Buy All Natural Antler Dog Chews" title="Buy All Natural Antler Dog Chews" src="assets/buy-antler-dog-chews.jpg" alt="" /></div><div class="content">
								<h2>Order Antler Dog Chews!! </h2>
								<p>If you're looking for an all natural antler dog chew Shed Finder is your place!</p>
                            <ul class="actions">
                                <li><span class="button special"><%= link_to "Order Antler Chews", controller: "users", action: "new", id: @users %></span></li>
							</ul>
							</div>
						</section>
					</section>

				<!-- Three -->
					<section id="three" class="wrapper style3 special">
						<div class="inner">
							<header class="major">
								<h1>Welcome to Shed Finder </h1>
								<p>Shed finder brings buyers and sellers together in one convenient location.<br />
								Whether you are a shed antler buyer or a shed antler seller,<br />
                                    we make it easy to find what you need. </p>
							</header>
							<ul class="features">
								<li class="icon fa-usd">
									<h3>Why sell with us?</h3>
									<p> Shed prices are always changing, so allowing multiple buyers to compete for your shed antlers insures you get the most for your money.</p>
								</li>
								<li class="icon fa-money">
									<h3>Why buy with us?</h3>
                                    <p>We bring you leads that you may never have found. It's <span class="yellow">FREE</span> to sign up and we only collect a small fee if you win the bid.</p>
								</li>
								<li class="icon fa-wrench">
									<h3>How does it work for sellers?</h3>
                                    <p>List your shed antlers or antler related product online for <span class="yellow">FREE</span> and start getting offers via text message and/or email.</p>
								</li>
								<li class="icon fa-shopping-cart">
									<h3>How does it work for buyers?</h3>
                                    <p>Sign up for <span class="yellow">FREE</span> and get listings via email or texts. Place an offer and if the seller accepts your bid you will be sent their contact information.</p>
								</li>
								<li class="icon fa-smile-o">
									<h3>Buy antler dog chews</h3>
									<p>All of our dog chews are all natural and cut by Shed Finder. Please visit our <%= link_to "antler dog chews",  buy_antler_dog_chews_path %> page for more information.</p>
								</li>
								<li class="icon fa-comments-o">
									<h3>Contact Us</h3>
                                    <p>If you would like more information or have additional questions please <%= link_to "Contact Us", controller: "messages", action: "new", id: @messages %>.</p>
								</li>
							</ul>
						</div>
					</section>

				<!-- CTA -->
					<section id="cta" class="wrapper style4">
						<div class="inner">
							<header>
								<h2>Make extra money</h2>
                                <p>It's <span class="yellow">FREE</span> and easy plus there is no obligation.</p>
							</header>
							<ul class="actions vertical">
								<li><span class="button fit special"><%= link_to "Sign Up", controller: "users", action: "new", id: @users %></span></li>
								<li><span class="button fit"><%= link_to "Contact Us", controller: "messages", action: "new", id: @messages %></span></li></li>
							</ul>
						</div>
					</section>
                    <%= render 'layouts/footer' %>

app/views/html_pages/signup_success.html.erb
<% provide(:title, "Shed Finder Sign Up Success!") %>

<!-- Main -->
					<article id="main">
						<header>
							<h1>Shed Finder Sign Up Success!</h1>
						</header>
						<section class="wrapper style5">
							<div class="inner">

                            <p>
                                <span style="font-size:35px;" class="green">Success! You are now logged in.</span>
                            </p>

							</div>
						</section>
					</article>
<%= render 'layouts/footer' %>

app/views/layouts/_menu.html.erb
<!-- Header -->
        <header id="header" class="alt">
            <% if current_user %>
            &nbsp;Welcome <%= link_to current_user.name, '/user_dashboard' %> | <%= link_to "Logout", '/logout' %>
            <% else %>
               <img style="margin:5px 0px 0px 10px; width:auto; max-height: 80%;" src="/assets/ShedFinder.png" alt="" />
            <% end %>
            <nav id="nav">
                <ul>
                    <li class="special">
                        <a href="#menu" class="menuToggle"><span>Menu</span></a>
                        <div id="menu">
                            <ul>
                                <li><i class="fa fa-home"></i><%= link_to "Home",  root_path %></li>
                                <li><i class="fa fa-user"></i><%= link_to "About", about_shed_finder_path %></li>
                                <li><i class="fa fa-money"></i><%= link_to "Sellers",  sell_shed_antlers_path %></li>
                                <li><i class="fa fa-shopping-cart"></i><%= link_to "Buyers",  buy_shed_antlers_path %></li>
                                <li><i class="fa fa-cutlery"></i><%= link_to "Antler Dog Chews", controller: "chew_orders", action: "new", id: @cheworder %></li>
                                <li><i class="fa fa-pencil"></i><%= link_to "Sign Up", controller: "users", action: "new", id: @users %></li>
                                <li><i class="fa fa-key"></i><%= link_to "Log In",  login_path %></li>
                                <li><i class="fa fa-dot-circle-o"></i><%= link_to "Contact Us", controller: "messages", action: "new", id: @messages %></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </nav>
        </header>

app/views/listings/new.html.erb
<h1>Listings#new</h1>
<p>Find me in app/views/listings/new.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title, "Edit Profile") %>
<%= render 'layouts/user_form' %>
<%= render 'layouts/footer' %>